import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getData } from "./_lib/data-source";
import Link from "next/link";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const main = await getData();

  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col gap-4 items-start justify-between p-16 relative">
          <h1 className="w-full flex flex-row flex-wrap gap-4 bg-white/70 p-16">
            <span className="sm:grow text-xl font-extrabold"><Link href="/">{main.data.info.name}</Link></span>
            <span className="flex flex-row gap-4">
              <span className="text-lg font-semibold"><Link href="/info">Info</Link></span>
              <span className="text-lg font-semibold"><Link href="/menu">Menu</Link></span>
            </span>
          </h1>
          <div className="grow w-full">
           {children}
          </div>
          <Image
            src={main.data.info.image}
            alt=""
            fill
            className="-z-10 bg-center opacity-50"
          ></Image>
        </main>
      </body>
    </html>
  );
}
